services:
- postgresql
addons:
  code_climate:
    repo_token:
      secure: rHKRm9apsLJJxFYf1ZoylgOw+rpqdaPIxK+LeyJVYHhnFYMDpjl58wQwKx0zwv96NSITnwXChacfyHHFT/5QS+Htjmiro9F8bOfaUswBggG9BmWlrqJ4te94dlYVcbhgTEY37+9ZuzPK5RDA1zyGk/q4zAFme+dmy3JIkGH3MPs=
  apt:
    update: true
    packages:
    - libxml2-dev
    - libxslt1-dev
    - optipng
    - jpegoptim
cache:
  bundler: true
  yarn: true
  directories:
  - /home/travis/.rvm/
  - node_modules
language: ruby
rvm:
- 2.6.3
install:
- bundle install --path vendor/bundle --retry 3
- yarn install
before_script:
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.template config/secrets.yml
- cp config/application.yml.template config/application.yml
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rake db:create
- bundle exec rake db:schema:load
- travis_wait 30 bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: bp3xJOb795L63tCXYb6XbJmTI7fSquwT59z7QlcUi2lHID7gqNLnCBTtZHjRY1ASSvwqk+hbPj857JXZ3SpGL4mySM0BicKIC7iPIvECtnMQeeg3EBk7h0S5ZE/P00Xk03peWmpbRzClXSZS+kmsRxKREK3dJh6+jO7XNaRpg6w=
deploy:
  provider: heroku
  api_key:
    secure: lNHq3StXYbN68U/Jtzwi7DR2xdlZOlpxyGo3aKJyMlyCaqeHelZm0YudVyslmpD/gBzEY97jh9njlqRRbzRL56s6dvBN1jcLYsd6/pY1aOAzNXkM1uzQfec/8IcP9jNYJTiY3cioPf3BLkcWHKVZhw14fQzEmG3Tc+jPe4iy8lY=
  app: it52
  on:
    repo: NNRUG/it52-rails
    branch: it52
  run:
  - "rake db:migrate"
  - restart
  - "rake cleanup"
