version: '2'
services:
  db:
    image: postgres:11.3-alpine
  redis:
    image: redis:alpine
  web:
    image: it52/rails:latest
    command: foreman start
    ports:
      - '5000:5000'
    links:
      - db
      - redis
    volumes:
      - .:/it52
    depends_on:
      - redis
      - db
