version: '2'
services:
  db:
    image: postgres:11.3-alpine
  memcached:
    image: memcached:alpine
  web:
    image: it52/rails:latest
    command: foreman start
    ports:
      - '5000:5000'
    links:
      - db
      - memcached
    volumes:
      - .:/it52
