---
groups:
  main:
    name: Всё о самом главном
    channels:
      it52info: IT события в Нижнем Новгороде
      nn_rug: lounge for developers since 2014 (тут в основном общий флудчат)
      It52forjuniors: Чат для тех кто только-только начинает свой путь в IT

  work:
    name: Предложения и поиск работы
    channels:
      jobsit52: Вакансии в IT Нижний Новгород
      js_nn_jobs: Вакансии для фронтовиков

  languages:
    name: По языкам программирования или платформам
    channels:
      rannts: Python
      pytho_nn: Python
      js_nn: Javascript
      nn_rug: Ruby
      jugnn: Java
      android_nn: Android (Java, Kotlin)
      iosnndevs: iOS (Objective-C, Swift)
      php_nn: PHP NN
      nnvdotnetchat: .Net (C#, F#)

  interests:
    name: По интересам
    channels:
      agile_nn: Сообщество Agile 
      cadr_hackerspace: Хакерспейс CADR
      defcon_nn_ch: новости ITSecurity
      defcon_nn: ITSecurity
      defcon_nn_offtop: ITSecurity offtop
      devops_nn: DevOps NN
      gamedevnn: Разработка игр в Нижнем Новгороде
      gdgnn: Google developers group
      jenkins_nn: Чат организаторов и активистов сообщества Jenkins в Нижнем Новгороде
      jenkins_ru_events: Анонсы событий в Jenkins
      it52startups: Cообщество для тех, у кого уже есть или кто задумывается создать свой startup
      itarchitect_nn: Сообщество "IT Architects" Нижнего Новгорода
      neimarkitlektoriy: IT-сообщество кампуса НЕЙМАРК
      nnlug: NN Linux user group
      nnov_globalcityhack: Чат участников Global City Hackathon
      nnodsbreakfast: Организация Open Data Science завтраков и чат на темы AI/ML/DS
      retrolan: LAN Party 2000 для гиков и фанатов олдскула. Некоммерческая тусовка по выходным
      russiachinese: Личный бложик айтишника из китайской компании
      startupdivisione: Клуб друзей, новаторов, инженеров, мечтателей и цифровых предпринимателей
      qalliance: Всё о тестировании
      qt_52: Чат QT сообщества