name: Docker build and push production
on:
  push:
    branches:
      - 'it52'
jobs:
  build-production:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile.production
          build-args: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: it52/rails:production
          cache-from: type=registry,ref=it52/rails:buildcache-prod
          cache-to: type=registry,ref=it52/rails:buildcache-prod,mode=max
