name: Docker build and push develpoment
on:
  push
jobs:
  build-development:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          build-args: RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: it52/rails:latest
          cache-from: type=registry,ref=it52/rails:buildcache-dev
          cache-to: type=registry,ref=it52/rails:buildcache-dev,mode=max
